[package]
name = "pic_url"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
mime_guess = "2.0"
